services:
  - type: web
    name: mihoutao-tracking-lookup
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
